### ISSUE TITLE
The ACPI parser causes the OS to panic and die

### ISSUE THREAD

**Issue by see-sharp265** [64/solstice#26]
The project outputs this when run: 
`   _____       _     _   _             Developed by:
 / ____|     | |   | | (_)              - Vinc
| (___   ___ | |___| |_ _  ___ ___      - Crally
 \___ \ / _ \| / __| __| |/ __/ _ \     - Mehodin
 ____) | (_) | \__ \ |_| | (_|  __/     - Alex8675
|_____/ \___/|_|___/\__|_|\___\___|

[DEBUG] gdt: loaded
[DEBUG] idt: loaded
[DEBUG] pmm: initialised
[DEBUG] acpi: found tables
[ERROR] panicked at 'not yet implemented', /home/[REDACTED]/.cargo/registry/src/github.com-[REDACTED]/aml_parser-0.3.0/src/name_object.rs:79:28`

The offending bit of code seems to be `
pub fn name_string<'a, 'c>() -> impl Parser<'a, 'c, AmlName>
where
    'c: 'a,
{
    /*
     * NameString := <RootChar('\') NamePath> | <PrefixPath NamePath>
     * PrefixPath := Nothing | <'^' PrefixPath>
     */
    let root_name_string = opcode(ROOT_CHAR).then(name_path()).map(|((), ref name_path)| {
        let mut name = alloc::vec![NameComponent::Root];
        name.extend_from_slice(name_path);
        Ok(AmlName(name))
    });

    // TODO: combinator to select a parser based on a peeked byte?
    comment_scope_verbose("NameString", move |input: &'a [u8], context| {
        let first_char = match input.first() {
            Some(&c) => c,
            None => return Err((input, context, AmlError::UnexpectedEndOfStream)),
        };

        // TODO: parse <PrefixPath NamePath> where there are actually PrefixChars
        match first_char {
            ROOT_CHAR => root_name_string.parse(input, context),
            PREFIX_CHAR => unimplemented!(),
            _ => name_path().map(|path| Ok(AmlName(path))).parse(input, context),
        }
    })
}`

**Comment by see-sharp265** [comment]
NOTE: The Solstice header actually appears normal in the output, the brokenness there is GitHub's fault.

**Comment by 64** [comment]
yeah the AML parser is a massive WIP, i’ll probably just comment this out as we dont need it for APIC / SMP yet

**Comment by see-sharp265** [comment]
also, did i accidentally post an auth token or something, the `github.com-[REDACTED]` part of the file path seems awfully weird...

**Comment by 64** [comment]
probably just a commit hash, I wouldn’t worry about it
